### ISSUE TITLE
Compile error: undeclared identifier 'vorbis_version_string' in DependencyVersions.cpp on OSX

### ISSUE THREAD

**Issue by Vezzra** [freeorion/freeorion#1071]
### Environment
- **FreeOrion Version**: 0.4.6+ 4f3619b91b9071d5fb9b7fadc27a7a6fe058e879
- **Operating System**: OSX
- **Fetched as**
  - Compiled from source
### Description

When I try to build 4f3619b91b9071d5fb9b7fadc27a7a6fe058e879 on OSX, I get the following compile errors:

```
/Users/user/SoftwareProjekte/FO/src/util/DependencyVersions.cpp:51:30: error: use of undeclared identifier 'vorbis_version_string'; did you mean 'VorbisVersionString'?
        const char* retval = vorbis_version_string();
                             ^~~~~~~~~~~~~~~~~~~~~
                             VorbisVersionString
/Users/user/SoftwareProjekte/FO/src/util/DependencyVersions.cpp:50:17: note: 'VorbisVersionString' declared here
    std::string VorbisVersionString() {
                ^
/Users/user/SoftwareProjekte/FO/src/util/DependencyVersions.cpp:51:21: error: no viable conversion from 'std::string' (aka 'basic_string<char>') to 'const char *'
        const char* retval = vorbis_version_string();
                    ^        ~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by adrianbroher** [comment]
The SDK libvorbis version (1.1.1 - released 2004) doesn't contain that function.

**Comment by geoffthemedio** [comment]
Meaning the OSX SDK needs to be updated...?

**Comment by adrianbroher** [comment]
> Meaning the OSX SDK needs to be updated...?

That would be the right thing to do.

**Comment by Vezzra** [comment]
Replacing the old 1.1.1 version of the Vorbis framework with 1.3.5 solved the issue. SDK updated and uploaded.
