### PR TITLE
Fix compile error in GCC 5.4.0

### LINKED ISSUE #2720: FreeOrion does not compile in gcc 5.4.0
# Environment

* **FreeOrion Version**: Git 4195b0c
* **Operating System**: Ubuntu
* gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609

### Description

```
freeorion/UI/CUIControls.cpp: In constructor ‘StatisticIcon::StatisticIcon(std::shared_ptr<GG::Texture>, double, int, bool, GG::X, GG::Y)’:
freeorion/UI/CUIControls.cpp:1304:42: error: converting to ‘const value_type {aka const std::tuple<double, int, bool>}’ from initializer list would use explicit constructor ‘constexpr std::tuple< <template-parameter-1-1> >::tuple(_UElements&& ...) [with _UElements = {double&, int&, bool&}; <template-parameter-2-2> = void; _Elements = {double, int, bool}]’
     m_values(1, {value, digits, showsign})
```

### Expected Result

I expect the source code to compile.

### Steps to reproduce

* Compile the mentioned FreeOrion version with the mentioned compiler.

### PR DESCRIPTION
**Pull request by geoffthemedio**
Hopefully fixes #2720

### CODE REVIEW

**Comment by Vezzra** [comment]
In case we do a RC2, should this be cherry picked?

Just in case. As no issues have turned up until now, it seems very unlikely that we're going to need another release candidate...

**Comment by geoffthemedio** [comment]
I think the changes are a fix to changes that weren't cherry picked to release, so picking this fi doesn't make sense / isn't actually possible.

There is https://github.com/freeorion/freeorion/issues/2719 which may be narrow enough to ignore, but which I'm still investigating.

**Comment by Vezzra** [comment]
Ok.
