### ISSUE TITLE
Linking failure with boost 1.83.0: multiple definition of `boost::phoenix::placeholders::uarg1

### ISSUE THREAD

**Issue by travier** [freeorion/freeorion#4707]
Bug Report
==========

Environment
-----------
* **FreeOrion Version**: v0.5
* **Operating System**: Linux (org.freedesktop.Platform 22.08 Flatpak SDK/Runtime)
* **Graphic card used**: N/A
* **Fetched as**
  * Compiled from source

Description
-----------

Linking with boost 1.83.0 fails with:
```
[281/284] Linking CXX shared library libfreeorionparse.so
FAILED: libfreeorionparse.so 
: && /usr/bin/ccache /usr/bin/c++ -fPIC -O2 -g -pipe -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -O3 -DNDEBUG  -L/app/lib -Wl,-z,relro,-z,now -Wl,--as-needed -shared -Wl,-soname,libfreeorionparse.so -o libfreeorionparse.so CMakeFiles/freeorionparseobj.dir/parse/ArithmeticRules.cpp.o CMakeFiles/freeorionparseobj.dir/parse/BuildingsParser.cpp.o CMakeFiles/freeorionparseobj.dir/parse/CommonParamsParser.cpp.o CMakeFiles/freeorionparseobj.dir/parse/ConditionParser1.cpp.o CMakeFiles/freeorionparseobj.dir/parse/ConditionParser2.cpp.o CMakeFiles/freeorionparseobj.dir/parse/ConditionParser3.cpp.o CMakeFiles/freeorionparseobj.dir/parse/ConditionParser4.cpp.o CMakeFiles/freeorionparseobj.dir/parse/ConditionParser5.cpp.o CMakeFiles/freeorionparseobj.dir/parse/ConditionParser6.cpp.o CMakeFiles/freeorionparseobj.dir/parse/ConditionParser7.cpp.o CMakeFiles/freeorionparseobj.dir/parse/ConditionParser.cpp.o CMakeFiles/freeorionparseobj.dir/parse/DoubleComplexValueRefParser.cpp.o CMakeFiles/freeorionparseobj.dir/parse/DoubleValueRefParser.cpp.o CMakeFiles/freeorionparseobj.dir/parse/EffectParser1.cpp.o CMakeFiles/freeorionparseobj.dir/parse/EffectParser2.cpp.o CMakeFiles/freeorionparseobj.dir/parse/EffectParser3.cpp.o CMakeFiles/freeorionparseobj.dir/parse/EffectParser4.cpp.o CMakeFiles/freeorionparseobj.dir/parse/EffectParser5.cpp.o CMakeFiles/freeorionparseobj.dir/parse/EffectParser.cpp.o CMakeFiles/freeorionparseobj.dir/parse/EffectPythonParser.cpp.o CMakeFiles/freeorionparseobj.dir/parse/EmpireStatsParser.cpp.o CMakeFiles/freeorionparseobj.dir/parse/EncyclopediaParser.cpp.o CMakeFiles/freeorionparseobj.dir/parse/EnumParser.cpp.o CMakeFiles/freeorionparseobj.dir/parse/EnumPythonParser.cpp.o CMakeFiles/freeorionparseobj.dir/parse/FieldsParser.cpp.o CMakeFiles/freeorionparseobj.dir/parse/FleetPlansParser.cpp.o CMakeFiles/freeorionparseobj.dir/parse/GameRulesParser.cpp.o CMakeFiles/freeorionparseobj.dir/parse/IntComplexValueRefParser.cpp.o CMakeFiles/freeorionparseobj.dir/parse/IntValueRefParser.cpp.o CMakeFiles/freeorionparseobj.dir/parse/ItemsParser.cpp.o CMakeFiles/freeorionparseobj.dir/parse/Lexer.cpp.o CMakeFiles/freeorionparseobj.dir/parse/MonsterFleetPlansParser.cpp.o CMakeFiles/freeorionparseobj.dir/parse/NamedValueRefParser.cpp.o CMakeFiles/freeorionparseobj.dir/parse/Parse.cpp.o CMakeFiles/freeorionparseobj.dir/parse/PlanetEnvironmentValueRefParser.cpp.o CMakeFiles/freeorionparseobj.dir/parse/PlanetSizeValueRefParser.cpp.o CMakeFiles/freeorionparseobj.dir/parse/PlanetTypeValueRefParser.cpp.o CMakeFiles/freeorionparseobj.dir/parse/PoliciesParser.cpp.o CMakeFiles/freeorionparseobj.dir/parse/ReportParseError.cpp.o CMakeFiles/freeorionparseobj.dir/parse/ShipDesignsParser.cpp.o CMakeFiles/freeorionparseobj.dir/parse/ShipHullsParser.cpp.o CMakeFiles/freeorionparseobj.dir/parse/ShipPartsParser.cpp.o CMakeFiles/freeorionparseobj.dir/parse/SpecialsParser.cpp.o CMakeFiles/freeorionparseobj.dir/parse/SpeciesParser.cpp.o CMakeFiles/freeorionparseobj.dir/parse/StarTypeValueRefParser.cpp.o CMakeFiles/freeorionparseobj.dir/parse/StringComplexValueRefParser.cpp.o CMakeFiles/freeorionparseobj.dir/parse/StringValueRefParser.cpp.o CMakeFiles/freeorionparseobj.dir/parse/TechsParser.cpp.o CMakeFiles/freeorionparseobj.dir/parse/UniverseObjectTypeValueRefParser.cpp.o CMakeFiles/freeorionparseobj.dir/parse/ValueRefParser.cpp.o CMakeFiles/freeorionparseobj.dir/parse/ValueRefPythonParser.cpp.o CMakeFiles/freeorionparseobj.dir/parse/VisibilityValueRefParser.cpp.o CMakeFiles/freeorionparseobj.dir/parse/PythonParser.cpp.o CMakeFiles/freeorionparseobj.dir/parse/SourcePythonParser.cpp.o CMakeFiles/freeorionparseobj.dir/parse/ConditionPythonParser.cpp.o  -Wl,-rpath,:::::::::::::::::: && :
/usr/lib/gcc/x86_64-unknown-linux-gnu/12.2.0/../../../../x86_64-unknown-linux-gnu/bin/ld: CMakeFiles/freeorionparseobj.dir/parse/BuildingsParser.cpp.o:(.bss+0x0): multiple definition of `boost::phoenix::placeholders::uarg10'; CMakeFiles/freeorionparseobj.dir/parse/ArithmeticRules.cpp.o:(.bss+0x0): first defined here
/usr/lib/gcc/x86_64-unknown-linux-gnu/12.2.0/../../../../x86_64-unknown-linux-gnu/bin/ld: CMakeFiles/freeorionparseobj.dir/parse/BuildingsParser.cpp.o:(.bss+0x2): multiple definition of `boost::phoenix::placeholders::uarg9'; CMakeFiles/freeorionparseobj.dir/parse/ArithmeticRules.cpp.o:(.bss+0x2): first defined here
/usr/lib/gcc/x86_64-unknown-linux-gnu/12.2.0/../../../../x86_64-unknown-linux-gnu/bin/ld: CMakeFiles/freeorionparseobj.dir/parse/BuildingsParser.cpp.o:(.bss+0x4): multiple definition of `boost::phoenix::placeholders::uarg8'; CMakeFiles/freeorionparseobj.dir/parse/ArithmeticRules.cpp.o:(.bss+0x4): first defined here
/usr/lib/gcc/x86_64-unknown-linux-gnu/12.2.0/../../../../x86_64-unknown-linux-gnu/bin/ld: CMakeFiles/freeorionparseobj.dir/parse/BuildingsParser.cpp.o:(.bss+0x6): multiple definition of `boost::phoenix::placeholders::uarg7'; CMakeFiles/freeorionparseobj.dir/parse/ArithmeticRules.cpp.o:(.bss+0x6): first defined here
/usr/lib/gcc/x86_64-unknown-linux-gnu/12.2.0/../../../../x86_64-unknown-linux-gnu/bin/ld: CMakeFiles/freeorionparseobj.dir/parse/BuildingsParser.cpp.o:(.bss+0x8): multiple definition of `boost::phoenix::placeholders::uarg6'; CMakeFiles/freeorionparseobj.dir/parse/ArithmeticRules.cpp.o:(.bss+0x8): first defined here
/usr/lib/gcc/x86_64-unknown-linux-gnu/12.2.0/../../../../x86_64-unknown-linux-gnu/bin/ld: CMakeFiles/freeorionparseobj.dir/parse/BuildingsParser.cpp.o:(.bss+0xa): multiple definition of `boost::phoenix::placeholders::uarg5'; CMakeFiles/freeorionparseobj.dir/parse/ArithmeticRules.cpp.o:(.bss+0xa): first defined here
/usr/lib/gcc/x86_64-unknown-linux-gnu/12.2.0/../../../../x86_64-unknown-linux-gnu/bin/ld: CMakeFiles/freeorionparseobj.dir/parse/BuildingsParser.cpp.o:(.bss+0xc): multiple definition of `boost::phoenix::placeholders::uarg4'; CMakeFiles/freeorionparseobj.dir/parse/ArithmeticRules.cpp.o:(.bss+0xc): first defined here
/usr/lib/gcc/x86_64-unknown-linux-gnu/12.2.0/../../../../x86_64-unknown-linux-gnu/bin/ld: CMakeFiles/freeorionparseobj.dir/parse/BuildingsParser.cpp.o:(.bss+0xe): multiple definition of `boost::phoenix::placeholders::uarg3'; CMakeFiles/freeorionparseobj.dir/parse/ArithmeticRules.cpp.o:(.bss+0xe): first defined here
...
```

See full log in:
- Flathub PR to update boost from 1.81.0. to 1.83.0: https://github.com/flathub/org.freeorion.FreeOrion/pull/18
- x86_64 build: https://buildbot.flathub.org/#/builders/33/builds/7190
- Full log: https://buildbot.flathub.org/#/builders/33/builds/7190/steps/8/logs/stdio

Expected Result
---------------
Builds with Boost 1.83.0

Steps to reproduce
------------------
* Try to build with Boost 1.83.0

Thanks!

**Comment by geoffthemedio** [comment]
I made a branch of the SDK repository and built it with Boost 1.83, and then built FreeOrion with that SDK on Windows. There were no link errors. So, I'm not sure how to proceed... Perhaps @o01eg can have a look when he's available.

**Comment by l29ah** [comment]
I've succeeded building FO with boost-1.83.0 on my Gentoo as well.

**Comment by travier** [comment]
Arg, OK. I'll have to investigate. Thanks

**Comment by o01eg** [comment]
Looks like it boost issue again https://github.com/boostorg/phoenix/issues/111#issuecomment-1694718712

**Comment by geoffthemedio** [comment]
Is there anything we can do in FreeOrion code / build system to fix this without requiring patching Boost before building or something like marking certain Boost versions as not allowed? If not, then I suppose this can be closed as won't fix?

**Comment by o01eg** [comment]
It looks like it works on some 1.83 boost versions so I'm not sure if we can do anything.

**Comment by travier** [comment]
I'm trying a build with boost 1.84.0 in https://github.com/flathub/org.freeorion.FreeOrion/pull/20

**Comment by travier** [comment]
This is fixed for me with boost 1.84.0. Thanks!
