### PR TITLE
Fix compatibility with ubuntu 16.04 xenial

### LINKED ISSUE #3172: compiling fails for boost 1.58
Bug Report
==========

The compilation of FreeOrion 4ce1758 from source code fails.

```
/freeorion/GG/src/dialogs/ColorDlg.cpp: In member function ‘virtual void GG::ColorDlg::CompleteConstruction()’:
/freeorion/GG/src/dialogs/ColorDlg.cpp:610:18: error: ‘boost::placeholders’ has not been declared
     using boost::placeholders::_1;
                  ^
/freeorion/GG/src/dialogs/ColorDlg.cpp:611:18: error: ‘boost::placeholders’ has not been declared
     using boost::placeholders::_2;
                  ^
/freeorion/GG/src/dialogs/ColorDlg.cpp:612:18: error: ‘boost::placeholders’ has not been declared
     using boost::placeholders::_3;
                  ^
/freeorion/GG/src/dialogs/FileDlg.cpp: In member function ‘virtual void GG::FileDlg::CompleteConstruction()’:
/freeorion/GG/src/dialogs/FileDlg.cpp:202:27: error: ‘placeholders’ is not a namespace-name
     namespace ph = boost::placeholders;
                           ^
/freeorion/GG/src/dialogs/FileDlg.cpp:202:39: error: expected namespace-name before ‘;’ token
     namespace ph = boost::placeholders;
                                       ^
/freeorion/GG/src/dialogs/FileDlg.cpp:206:92: error: ‘ph’ has not been declared
     m_files_list->SelRowsChangedSignal.connect(boost::bind(&FileDlg::FileSetChanged, this, ph::_1));
                                                                                            ^
/freeorion/GG/src/dialogs/FileDlg.cpp:207:97: error: ‘ph’ has not been declared
     m_files_list->DoubleClickedRowSignal.connect(boost::bind(&FileDlg::FileDoubleClicked, this, ph::_1, ph::_2, ph::_3));
                                                                                                 ^
/freeorion/GG/src/dialogs/FileDlg.cpp:207:105: error: ‘ph’ has not been declared
     m_files_list->DoubleClickedRowSignal.connect(boost::bind(&FileDlg::FileDoubleClicked, this, ph::_1, ph::_2, ph::_3));
                                                                                                         ^
/freeorion/GG/src/dialogs/FileDlg.cpp:207:113: error: ‘ph’ has not been declared
     m_files_list->DoubleClickedRowSignal.connect(boost::bind(&FileDlg::FileDoubleClicked, this, ph::_1, ph::_2, ph::_3));
                                                                                                                 ^
/freeorion/GG/src/dialogs/FileDlg.cpp:208:86: error: ‘ph’ has not been declared
     m_files_edit->EditedSignal.connect(boost::bind(&FileDlg::FilesEditChanged, this, ph::_1));
                                                                                      ^
/freeorion/GG/src/dialogs/FileDlg.cpp:209:88: error: ‘ph’ has not been declared
     m_filter_list->SelChangedSignal.connect(boost::bind(&FileDlg::FilterChanged, this, ph::_1));
                                                                                        ^
/freeorion/universe/Fleet.cpp: In function ‘std::__cxx11::list<int> {anonymous}::TruncateRouteToEndAtSystem(const std::__cxx11::list<int>&, int, int)’:
/freeorion/universe/Fleet.cpp:70:85: error: ‘boost::placeholders’ has not been declared
                                    boost::bind(&SystemHasNoVisibleStarlanes, boost::placeholders::_1, empire_id));
                                                                                     ^
/freeorion/universe/Conditions.cpp:51:18: error: ‘boost::placeholders’ has not been declared
     using boost::placeholders::_1;
                  ^
```

Environment
-----------

* **FreeOrion Version**: 4ce1758
* **Operating System**: Ubuntu 16.04 LTS
* **Fetched as**
  * Compiled from source
* Boost 1.58
* GCC (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609

Description
-----------

The source code does not compile, see above.

Expected Result
---------------

The source code shall compile.

Steps to reproduce
------------------

* mkdir build
* cd build
* ccmake ..
* make

### PR DESCRIPTION
**Pull request by o01eg**
Fixes #3172

### CODE REVIEW

**Review by Vezzra — APPROVED** [review]
I can't really comment on the actual code changes - as far as I can tell, those look ok.

Concerning the intent to fix compatibility with Ubuntu 16.04 LTS, I have no objections. Trying to make 0.4.10.1 work with that LTS release sounds reasonable.

It will of course require a third release candidate for 0.4.10.1.

**Comment by geoffthemedio** [comment]
seems to still work with Boost 1.74

**Review by geoffthemedio — APPROVED** [review]

**Comment by Vezzra** [comment]
Can we merge this? It's kind of needed for RC3 - if this isn't merged within the next two hours, I'll have to postpone RC3 until Sunday...

**Comment by o01eg** [comment]
Yes, I think. It doesn't raise other concerns I see.

**Comment by Vezzra** [comment]
#3172 can be closed as resolved I assume?

**Comment by o01eg** [comment]
Yes, it's strange it wasn't closed automatically.
