### ISSUE TITLE
FreeOrion does not compile in gcc 5.4.0

### ISSUE THREAD

**Issue by aschuch247** [freeorion/freeorion#2720]
# Environment

* **FreeOrion Version**: Git 4195b0c
* **Operating System**: Ubuntu
* gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609

### Description

```
freeorion/UI/CUIControls.cpp: In constructor ‘StatisticIcon::StatisticIcon(std::shared_ptr<GG::Texture>, double, int, bool, GG::X, GG::Y)’:
freeorion/UI/CUIControls.cpp:1304:42: error: converting to ‘const value_type {aka const std::tuple<double, int, bool>}’ from initializer list would use explicit constructor ‘constexpr std::tuple< <template-parameter-1-1> >::tuple(_UElements&& ...) [with _UElements = {double&, int&, bool&}; <template-parameter-2-2> = void; _Elements = {double, int, bool}]’
     m_values(1, {value, digits, showsign})
```

### Expected Result

I expect the source code to compile.

### Steps to reproduce

* Compile the mentioned FreeOrion version with the mentioned compiler.

**Comment by geoffthemedio** [comment]
Does #2721 fix it?

**Comment by aschuch247** [comment]
I rebased to that branch and FreeOrion compiles. Thanks!

**Comment by adrianbroher** [comment]
Thats not the Ubuntu 16.04 stock G++ compiler version.

**Comment by Vezzra** [comment]
> Thats not the Ubuntu 16.04 stock G++ compiler version.

Which anwers my question if this issue needs to be fixed for 0.4.9, which would make another release candidate necessary. Obviously that's not the case.

**Comment by o01eg** [comment]
https://packages.ubuntu.com/xenial/g++

Looks like G++ compiler in 16.04 is even older.
