### ISSUE TITLE
Build failure with boost-1.61

### ISSUE THREAD

**Issue by houseofsuns** [freeorion/freeorion#777]
On my gentoo amd64 machine with gcc-5.4.0 I see the following build failure with boost-1.61.

<pre>
/var/tmp/portage/games-strategy/freeorion-0.4.5/work/freeorion-0.4.5/parse/EffectParser5.cpp:27:17:   required from here
/usr/include/boost/spirit/home/qi/detail/alternative_function.hpp:30:46: error: no type named ‘types’ in ‘boost::spirit::qi::detail::find_substitute<boost::optional<boost::variant<std::vector<Effect::EffectBase*>, Effect::EffectBase*, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> >, Effect::EffectBase*>::variant_type {aka class boost::optional<boost::variant<std::vector<Effect::EffectBase*>, Effect::EffectBase*, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> >}’
         typedef typename variant_type::types types;
</pre>

As well as

<pre>
In file included from /var/tmp/portage/games-strategy/freeorion-0.4.5/work/freeorion-0.4.5/util/SerializeUniverse.cpp:8:0:
/usr/include/boost/archive/detail/iserializer.hpp: In instantiation of ‘static void boost::archive::detail::heap_allocation<T>::doesnt_have_new_operator::invoke_delete(T*) [with T = Ship]’:
/usr/include/boost/archive/detail/iserializer.hpp:265:33:   required from ‘static void boost::archive::detail::heap_allocation<T>::invoke_delete(T*) [with T = Ship]’
/usr/include/boost/archive/detail/iserializer.hpp:273:26:   required from ‘boost::archive::detail::heap_allocation<T>::~heap_allocation() [with T = Ship]’
/usr/include/boost/archive/detail/iserializer.hpp:294:36:   required from ‘void* boost::archive::detail::pointer_iserializer<Archive, T>::heap_allocation() const [with Archive = boost::archive::binary_iarchive; T = Ship]’
/var/tmp/portage/games-strategy/freeorion-0.4.5/work/freeorion-0.4.5/util/SerializeUniverse.cpp:326:133:   required from here
/var/tmp/portage/games-strategy/freeorion-0.4.5/work/freeorion-0.4.5/util/../universe/Ship.h:99:5: error: ‘virtual Ship::~Ship()’ is protected
     ~Ship() {}
     ^
</pre>

**Comment by houseofsuns** [comment]
[freeorion-0.4.5:20160718-185547.txt](https://github.com/freeorion/freeorion/files/376634/freeorion-0.4.5.20160718-185547.txt)
And here is the complete build log.

**Comment by geoffthemedio** [comment]
Appears to be a duplicate of https://github.com/freeorion/freeorion/issues/670

**Comment by houseofsuns** [comment]
There the resolution was that it may be a Mageia packaging issue, which is certainly not true here. If I would have to make a wild guess I would say some API change in boost (it worked fine with boost-1.60).

**Comment by geoffthemedio** [comment]
The resolution was that it seems like a problem with Boost introduced in 1.61, which is similar to a problem that occurred in another version 8 years ago, and probably not something we need/should modify FreeOrion code to fix.

Coincidentally the Mageia people decided to stick with Boost 1.60 for their next release, making the issue not important for the short term.

Regardless, can you try moving the declaration of ~Ship to the public section of its header? Seems odd that it's only an issue for Ship since various other similar classes have the destructors declared and used the same way.

**Comment by houseofsuns** [comment]
The following patch silenced all errors of the second kind. However the build still fails because of the errors of the first kind. And I've no clue what they mean.

[0001-Make-destructors-public.txt](https://github.com/freeorion/freeorion/files/376805/0001-Make-destructors-public.txt)

**Comment by geoffthemedio** [comment]
Looks like a Boost / compiler error / incompatibility.

**Comment by Vezzra** [comment]
@geoffthemedio: shall we apply the patch provided by @veelai? Besides that, as far as the remaining issue is concerned, any chance for us to fix that, or is it a wontfix?

**Comment by geoffthemedio** [comment]
It's one of those deep-in-Boost type bugs that are problematic to resolve. I / one would just have to start rebuilding the parsers and see what causes it to suddenly have problems. No idea how complicated it would end up being.

Applying the other patch doesn't have much point though, if the other Boost 1.61 issue(s) remain...

I'd also vaguely guess that the destructors were made private to emphasize that most code shouldn't be deleting UniverseObject or derived-class objects directly, but rather let the containing smart pointers deal with that...

**Comment by Vezzra** [comment]
Ok, leaving the 0.4.6 milestone for now. If this turns out to be too complicated to fix, we can still switch to the post release milestone or close it as wontfix.

**Comment by ArsenShnurkov** [comment]
was this bug reported to boost project? if yes, then what is it number?

I created a new one (because i was unable to find something similar):
https://svn.boost.org/trac/boost/ticket/12349

here is my full log - http://pastehtml.com/view/gn17nmexx.html

**Comment by Vezzra** [comment]
> was this bug reported to boost project?

Not by one of us, not that I know of.

**Comment by asm64** [comment]
Hello. I read fluently FO code. I'm not sure, but what if we move constructors and destructors from protected to public. I think it is visibility problem..

**Comment by geoffthemedio** [comment]
Moving destructors to public was suggested and implemented in the patch posted above, and fixes that set of compile errors, having to do with Boost serialization.

However, it doesn't fix the "no type named ‘types’" problem, occurring within Boost Spirit code.

Moving the structors also shouldn't be needed, I think, as it works fine in previous Boost versions, and they are plausibly better to keep protected/private to clarify usage of the classes.

**Comment by asm64** [comment]
I saw everything - it is boost problem.

**Comment by Vezzra** [comment]
Boost is a powerful cross platform library, but the issues that get introduced frequently with new versions are somewhat annoying...

**Comment by dracwyrm** [comment]
Gentoo compiles Boost with C++98 standard. Does this game compile as C++11 by default? Or use the default set by GCC 5.x, which is C++11? If so, then this is the issue and compatibility. Boost must be compiled with the same ABI as 1.61 added in C++11 code that is pulled in by a program, which then causes issues as the base of Boost is C++98. Compiling Free Orion with C++98 should fix the issue for now. However, Boost 1.62 will be switched to C++11 in Gentoo.

**Comment by geoffthemedio** [comment]
I believe the problem is happening at the compilation stage, not linking. Would ABI issues exist then?

**Comment by apoleon** [comment]
Debian is also affected because Boost 1.61 is now the new default. 

Debian bug: https://bugs.debian.org/833773

Build log for amd64: https://buildd.debian.org/status/fetch.php?pkg=freeorion&arch=amd64&ver=0.4.5%2Bgit20160707-1%2Bb1&stamp=1470433494

I have left a comment for the Boost bug report at https://svn.boost.org/trac/boost/ticket/12349

**Comment by houseofsuns** [comment]
I tried adding -std=gnu++98 in the build process and got the same errors as before.

**Comment by Vezzra** [comment]
I wonder if we'll have to address that issue after all, as annoying as it is to have to do that. But it seems, as more (and important) Linux distros (like Debian) are switching to Boost 1.61, that FO won't build on many, if not most Linux systems, which is not a good thing IMO.

Unfortunately I have no idea what to do to fix this. 😦

**Comment by asm64** [comment]
Well, why so discouraged, my friends? There is a problem to be solved. So we all need to come together and ask the developers of the library component "spirit" (Joel de Guzman and Hartmut Kaiser). I sent a confirmation error. I suggest to all cosmic races to bury the hatchet and unite to send confirmation of the problem here https://svn.boost.org/trac/boost/ticket/12349.

**Comment by Vezzra** [comment]
No one is wielding any hatchets here 😉 

But this isn't the first time we have to deal with weird boost issues, and usually we had to address it by adding some boost-version-specific workarounds/fixes to our code, because IIRC we had to wait for the next boost release to see those fixes on the boost side of things.

Meaning, building FO against that particular boost version was broken. A problem for everyone who was on a Linux distro and version that used said boost version. So we had put in the required fixes into our code.

Which doesn't mean that we shouldn't report the bug (and send confirmations), but I don't think this will spare us to have to come up with our own fixes.

**Comment by asm64** [comment]
Hatchets were due in the game battle :) Now we can not fight because of problems with the compilation :( 

I'm Gentoo user with amd64 and I want to play.. May be try to build older boost version and pass it to cmake? Something like this:
cmake -DCMAKE_INSTALL_PREFIX=$TARGET \
    -DBoost_NO_BOOST_CMAKE=TRUE \
    -DBoost_NO_SYSTEM_PATHS=TRUE \
    -DBOOST_ROOT:PATHNAME=$TARGET \
    -DBoost_LIBRARY_DIRS:FILEPATH=${TARGET}/lib
And may be also try to speed up running with static linking?
How do you think, will it work?

**Comment by adrianbroher** [comment]
Results so far:
- boost::spirit v 1.61 relies on the fact that the `Variant` template type of `boost::spirit::qi::detail::find_substitute` typedefs a `types` subtype.
- For the failing instantiation of `find_substition` a `boost::optional` is used as `Variant` template type.
- `boost::optional` removed its `types` subtype implementation with commit boostorg/optional@b5b8414c069a2c5f16cc1f9813d069c8b36e2c35, which means that this type is missing on every boost version 1.61 and onwards.
- boost up to 1.60 should work without problems.
- this is no C++11/98 ABI issue, but an `we rely on an outdated API` issue on the spirit side and maybe an `we removed some public API without considering all cases` issue on the boost::optional side.
- Also I won't rule out that FreeOrion uses an outdated API of boost::spirit but I need to investigate further.

So far it seems like this can't be worked around in our code @Vezzra.

**Comment by adrianbroher** [comment]
@asm64 

If you feel like it you can forward the information found so far.

**Comment by geoffthemedio** [comment]
@adrianbroher "we" = FreeOrion code relying on outdated boost::spirit code or "we" = boost::spirit code relying on outdated boost::optional code?

**Comment by adrianbroher** [comment]
@geoffthemedio

> "we" = FreeOrion code relying on outdated boost::spirit code.

This one. I updated the comment accordingly.

**Comment by Vezzra** [comment]
> So far it seems like this can't be worked around in our code

Which means we can only hope Boost will make a bugfix release for 1.61 instead of waiting for 1.62 to provide a fix.

Well, crap. 😦

**Comment by asm64** [comment]
May be try to include (parts of) working library into the main tree with the ability to choose a built-in / external? Boost looks like a dr..gs. Have dependence but there is no library аnd the supplier is often a problem :( I do not know a joke successful or not..

**Comment by dbenage-cx** [comment]
Is `BOOST_OPTIONAL_CONFIG_USE_OLD_IMPLEMENTATION_OF_OPTIONAL` a viable workaround/short-term fix here?

Using `-DBOOST_OPTIONAL_CONFIG_USE_OLD_IMPLEMENTATION_OF_OPTIONAL` and the patch above, I'm not seeing any issues off-hand (just checking a few windows, playing ~10 turns).

`Client : v0.4.5+ [build 2016-08-20.6181a4d] CMake`
`Client : Boost: 1_61`
GCC 6.1.1 20160621

**Comment by houseofsuns** [comment]
I can confirm, that this works in my setup.

**Comment by Vezzra** [comment]
Can the others who reported having these build failures with Boost 1.61 confirm that the fix @dbenage-cx suggested works for them? @ArsenShnurkov, @asm64, @dracwyrm?

Then maybe we can finally close this issue, as (judging by the discussion above) there is not much we can do about it.

Anyway, I'm going to remove the "Release 0.4.6" milestone now, as I don't want to block the release for something that apparently is more or less out of our power to fix.

**Comment by Vezzra** [comment]
As decided in the discussion of #851 ([see these comments](https://github.com/freeorion/freeorion/issues/851#issuecomment-241255590)), setting milestone to "Release v0.4.6" again for now.

**Comment by asm64** [comment]
For Gentoo users
Copy patch file to freeorion directory as user:
`$ cp 0001-Make-destructors-public.txt $FREEORION_DIR`

And build with script:

#/bin/bash
cd ./freeorion
patch -p1 < 0001-Make-destructors-public.txt
if [ -f "./CMakeCache.txt" ]; then rm -f CMakeCache.txt; fi
make clean
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-march=amdfam10 -O2 -msse -msse4a -mfpmath=sse -ftree-loop-if-convert -fsched-pressure -DBOOST_OPTIONAL_CONFIG_USE_OLD_IMPLEMENTATION_OF_OPTIONAL" .
make -j7

Works! I'll try w/o patch..

**Comment by geoffthemedio** [comment]
Does it work without rebuilding boost?

**Comment by houseofsuns** [comment]
@geoffthemedio Yes, I did not need to rebuild boost.

@asm64 There is an updated ebuild available for Gentoo via the official repo now.

**Comment by asm64** [comment]
Thanks veelai, I use GIT sources and manual compilation.

**Comment by Vezzra** [comment]
So, does that mean we can consider this particular issue solved and close it?

**Comment by geoffthemedio** [comment]
I think it would first require setting up a suitable case in CMake to set the extra define, and apparently applying the non-private destructors patch.

**Comment by adrianbroher** [comment]
The `protected desctructors` issue will be handled in #887

**Comment by l29ah** [comment]
Same problem with 1.62.0.
