### PR TITLE
Use OpenGL with GLVND - CMP0072

### PR DESCRIPTION
**Pull request by sevu**
Resolves this warning when compiling:
```
CMake Warning (dev) at /usr/share/cmake-3.20/Modules/FindOpenGL.cmake:315 (message):
Policy CMP0072 is not set: FindOpenGL prefers GLVND by default when
available.  Run "cmake --help-policy CMP0072" for policy details.  Use the
cmake_policy command to set the policy and suppress this warning.

FindOpenGL found both a legacy GL library:

OPENGL_gl_LIBRARY: /usr/lib/libGL.so

and GLVND libraries for OpenGL and GLX:

OPENGL_opengl_LIBRARY: /usr/lib/libOpenGL.so
OPENGL_glx_LIBRARY: /usr/lib/libGLX.so

OpenGL_GL_PREFERENCE has not been set to "GLVND" or "LEGACY", so for
compatibility with CMake 3.10 and below the legacy GL library will be used.
Call Stack (most recent call first):
CMakeLists.txt:273 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.
```

The policy was added in cmake 3.11, thus checking, if it exists.
The OPENGL_opengl_LIBRARY variable was added in 3.10, and can
be used without the policy being available.

Debian stable has cmake 3.13,
Debian oldstable can get 3.16 from the backports,
Ubuntu 18.04 uses cmake 3.10 (and has no backports).

Older cmake versions could also be supported by using the other method, which would end up with more branching.

### CODE REVIEW

**Comment by o01eg** [comment]
@sevu Test fails to build on Ubuntu 20.04 with 
```
 /usr/bin/ld: ../../libfo_acceptance_runner.a(Application.cpp.o): undefined reference to symbol 'glEnable'
```

**Comment by sevu** [comment]
Alright, everything fixed so far.

**Comment by geoffthemedio** [comment]
@o01eg OK?

**Comment by o01eg** [comment]
@geoffthemedio Yes
