### PR TITLE
Fix Boost.Phoenix issue for version 1.82 and greater

### LINKED ISSUE #4483: After upgrade boost to 1.82 Freeorion 0.5 no longer compile
Bug Report
==========

Environment
-----------

* **FreeOrion Version**: 0.5 stable
* **Operating System**: OpenMandriva Cooker
* **Fetched as** 
  * Compiled from source

Description
-----------

After upgrade system boost to 1.82, freeorion no longer compile. It compiles fine with previous boost 1.81.
Here is error message:
```
make[2]: Leaving directory '/builddir/build/BUILD/freeorion-0.5/build'
DEBUG util.py:443:  ld.lld: error: duplicate symbol: boost::phoenix::placeholders::uarg1
DEBUG util.py:443:  >>> defined in libfreeorionparse.a(BuildingsParser.cpp.o)
DEBUG util.py:443:  >>> defined in libfreeorionparse.a(VisibilityValueRefParser.cpp.o)
DEBUG util.py:443:  ld.lld: error: duplicate symbol: boost::phoenix::placeholders::uarg2
DEBUG util.py:443:  >>> defined in libfreeorionparse.a(BuildingsParser.cpp.o)
DEBUG util.py:443:  >>> defined in libfreeorionparse.a(VisibilityValueRefParser.cpp.o)
DEBUG util.py:443:  ld.lld: error: duplicate symbol: boost::phoenix::placeholders::uarg3
DEBUG util.py:443:  >>> defined in libfreeorionparse.a(BuildingsParser.cpp.o)
DEBUG util.py:443:  >>> defined in libfreeorionparse.a(VisibilityValueRefParser.cpp.o)
DEBUG util.py:443:  ld.lld: error: duplicate symbol: boost::phoenix::placeholders::uarg4
DEBUG util.py:443:  >>> defined in libfreeorionparse.a(BuildingsParser.cpp.o)
DEBUG util.py:443:  >>> defined in libfreeorionparse.a(VisibilityValueRefParser.cpp.o)
DEBUG util.py:443:  ld.lld: error: duplicate symbol: boost::phoenix::placeholders::uarg5
DEBUG util.py:443:  >>> defined in libfreeorionparse.a(BuildingsParser.cpp.o)
DEBUG util.py:443:  >>> defined in libfreeorionparse.a(VisibilityValueRefParser.cpp.o)
DEBUG util.py:443:  ld.lld: error: duplicate symbol: boost::phoenix::placeholders::uarg6
DEBUG util.py:443:  >>> defined in libfreeorionparse.a(BuildingsParser.cpp.o)
DEBUG util.py:443:  >>> defined in libfreeorionparse.a(VisibilityValueRefParser.cpp.o)
DEBUG util.py:443:  ld.lld: error: duplicate symbol: boost::phoenix::placeholders::uarg7
DEBUG util.py:443:  >>> defined in libfreeorionparse.a(BuildingsParser.cpp.o)
DEBUG util.py:443:  >>> defined in libfreeorionparse.a(VisibilityValueRefParser.cpp.o)
DEBUG util.py:443:  ld.lld: error: duplicate symbol: boost::phoenix::placeholders::uarg8
```

Here is a full build log: https://file-store.openmandriva.org/api/v1/file_stores/1b971659976dcdbb1f168f154001af880af8e187.log?show=true

Also this looks similar to #4440 but it was resolved for boost 1.81...

Expected Result
---------------

Freeorion compile fine with latest boost 1.82

Steps to reproduce
------------------

* Upgrade boost to 1.82
* Make sure to use Clang 16 compiler
* Compile freeorion 0.5
* See compilation error

### PR DESCRIPTION
**Pull request by o01eg**
Should fix #4483

### CODE REVIEW

**Comment by geoffthemedio** [comment]
Looks reasonable...
