### ISSUE TITLE
Fails to build with Boost 1.70 (Beta1)

### ISSUE THREAD

**Issue by jbeich** [freeorion/freeorion#2409]
Regressed by boostorg/asio@a72fbb0b867f:
```c++
network/ServerNetworking.cpp:691:42: error: no member named 'get_io_service' in
      'boost::asio::basic_socket_acceptor<boost::asio::ip::tcp, boost::asio::executor>'
            m_player_connection_acceptor.get_io_service(),
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
1 error generated.
```

**Comment by geoffthemedio** [comment]
Try replacing that line with
`m_player_connection_acceptor.get_executor().context(),`

**Comment by jbeich** [comment]
```c++
network/ServerNetworking.cpp:691:13: error: non-const lvalue reference to type 'boost::asio::io_service'
      (aka 'boost::asio::io_context') cannot bind to a value of unrelated type 'boost::asio::execution_context'
            m_player_connection_acceptor.get_executor().context(),
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
network/ServerNetworking.cpp:221:78: note: passing argument to parameter 'io_service' here
PlayerConnectionPtr PlayerConnection::NewConnection(boost::asio::io_service& io_service,
                                                                             ^
```

**Comment by geoffthemedio** [comment]
Try with https://github.com/freeorion/freeorion/pull/2410 applied?

**Comment by jbeich** [comment]
```c++
network/ServerNetworking.cpp:691:13: error: non-const lvalue reference to type 'boost::asio::io_context' cannot
      bind to a value of unrelated type 'boost::asio::execution_context'
            m_player_connection_acceptor.get_executor().context(),
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
network/ServerNetworking.cpp:221:78: note: passing argument to parameter 'io_context' here
PlayerConnectionPtr PlayerConnection::NewConnection(boost::asio::io_context& io_context,
                                                                             ^
```

**Comment by geoffthemedio** [comment]
Apparently `basic_socket_acceptor` has an extra template parameter in Boost 1.70
https://www.boost.org/doc/libs/1_70_0_beta1/doc/html/boost_asio/reference/basic_socket_acceptor.html
https://www.boost.org/doc/libs/1_69_0/doc/html/boost_asio/reference/basic_socket_acceptor.html

Consequently the return type of `get_executor` has changed from `io_context::executor_type` to `execution_context` by default. I don't have a 1.70 environment to test, so all I can do is speculatively suggest
````
#if BOOST_VERSION >= 107000
    boost::asio::basic_socket_acceptor<boost::asio::ip::tcp, boost::asio::io_context::executor_type>
                                    m_player_connection_acceptor;
#else
    boost::asio::ip::tcp::acceptor  m_player_connection_acceptor;
#endif
````
around [line 184 of ServerNetworking.h](https://github.com/freeorion/freeorion/blob/master/network/ServerNetworking.h#L184) to perhaps restore the old behaviour?

**Comment by jbeich** [comment]
On top of #2410? OK, that passes Boost.Asio issue but the build still fails.

Regressed by boostorg/gil@2308a1a85a7b:
```c++
GG/src/Texture.cpp:265:19: error: no member named 'move_in' in
      'boost::gil::any_image<boost::mpl::vector4<boost::gil::image<boost::gil::pixel<unsigned char,
      boost::gil::layout<boost::mpl::vector1<boost::gil::gray_color_t>, boost::mpl::range_c<int, 0, 1> > >, false,
      std::__1::allocator<unsigned char> >, boost::gil::image<boost::gil::pixel<unsigned char,
      boost::gil::layout<boost::mpl::vector2<boost::gil::gray_color_t, boost::gil::alpha_t>,
      boost::mpl::range_c<int, 0, 2> > >, false, std::__1::allocator<unsigned char> >,
      boost::gil::image<boost::gil::pixel<unsigned char, boost::gil::layout<boost::mpl::vector3<boost::gil::red_t,
      boost::gil::green_t, boost::gil::blue_t>, boost::mpl::range_c<int, 0, 3> > >, false,
      std::__1::allocator<unsigned char> >, boost::gil::image<boost::gil::pixel<unsigned char,
      boost::gil::layout<boost::mpl::vector4<boost::gil::red_t, boost::gil::green_t, boost::gil::blue_t,
      boost::gil::alpha_t>, boost::mpl::range_c<int, 0, 4> > >, false, std::__1::allocator<unsigned char> > > >'
            image.move_in(rgba_image);
            ~~~~~ ^
GG/src/Texture.cpp:291:5: error: no member named 'current_type_is' in
      'boost::gil::any_image<boost::mpl::vector4<boost::gil::image<boost::gil::pixel<unsigned char,
      boost::gil::layout<boost::mpl::vector1<boost::gil::gray_color_t>, boost::mpl::range_c<int, 0, 1> > >, false,
      std::__1::allocator<unsigned char> >, boost::gil::image<boost::gil::pixel<unsigned char,
      boost::gil::layout<boost::mpl::vector2<boost::gil::gray_color_t, boost::gil::alpha_t>,
      boost::mpl::range_c<int, 0, 2> > >, false, std::__1::allocator<unsigned char> >,
      boost::gil::image<boost::gil::pixel<unsigned char, boost::gil::layout<boost::mpl::vector3<boost::gil::red_t,
      boost::gil::green_t, boost::gil::blue_t>, boost::mpl::range_c<int, 0, 3> > >, false,
      std::__1::allocator<unsigned char> >, boost::gil::image<boost::gil::pixel<unsigned char,
      boost::gil::layout<boost::mpl::vector4<boost::gil::red_t, boost::gil::green_t, boost::gil::blue_t,
      boost::gil::alpha_t>, boost::mpl::range_c<int, 0, 4> > >, false, std::__1::allocator<unsigned char> > > >'
    IF_IMAGE_TYPE_IS(gil::gray8)
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
GG/src/Texture.cpp:283:15: note: expanded from macro 'IF_IMAGE_TYPE_IS'
    if (image.current_type_is<image_prefix ## _image_t>()) {            \
        ~~~~~ ^
GG/src/Texture.cpp:291:5: error: expected '(' for function-style cast or type construction
    IF_IMAGE_TYPE_IS(gil::gray8)
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
GG/src/Texture.cpp:283:55: note: expanded from macro 'IF_IMAGE_TYPE_IS'
    if (image.current_type_is<image_prefix ## _image_t>()) {            \
                              ~~~~~~~~~~~~~~~~~~~~~~~~^
GG/src/Texture.cpp:291:5: error: expected expression
GG/src/Texture.cpp:283:57: note: expanded from macro 'IF_IMAGE_TYPE_IS'
    if (image.current_type_is<image_prefix ## _image_t>()) {            \
                                                        ^
GG/src/Texture.cpp:291:5: error: no member named '_dynamic_cast' in
      'boost::gil::any_image<boost::mpl::vector4<boost::gil::image<boost::gil::pixel<unsigned char,
      boost::gil::layout<boost::mpl::vector1<boost::gil::gray_color_t>, boost::mpl::range_c<int, 0, 1> > >, false,
      std::__1::allocator<unsigned char> >, boost::gil::image<boost::gil::pixel<unsigned char,
      boost::gil::layout<boost::mpl::vector2<boost::gil::gray_color_t, boost::gil::alpha_t>,
      boost::mpl::range_c<int, 0, 2> > >, false, std::__1::allocator<unsigned char> >,
      boost::gil::image<boost::gil::pixel<unsigned char, boost::gil::layout<boost::mpl::vector3<boost::gil::red_t,
      boost::gil::green_t, boost::gil::blue_t>, boost::mpl::range_c<int, 0, 3> > >, false,
      std::__1::allocator<unsigned char> >, boost::gil::image<boost::gil::pixel<unsigned char,
      boost::gil::layout<boost::mpl::vector4<boost::gil::red_t, boost::gil::green_t, boost::gil::blue_t,
      boost::gil::alpha_t>, boost::mpl::range_c<int, 0, 4> > >, false, std::__1::allocator<unsigned char> > > >'
    IF_IMAGE_TYPE_IS(gil::gray8)
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
GG/src/Texture.cpp:286:30: note: expanded from macro 'IF_IMAGE_TYPE_IS'
            const_view(image._dynamic_cast<image_prefix ## _image_t>())); \
                       ~~~~~ ^
GG/src/Texture.cpp:291:5: error: expected '(' for function-style cast or type construction
    IF_IMAGE_TYPE_IS(gil::gray8)
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
GG/src/Texture.cpp:286:68: note: expanded from macro 'IF_IMAGE_TYPE_IS'
            const_view(image._dynamic_cast<image_prefix ## _image_t>())); \
                                           ~~~~~~~~~~~~~~~~~~~~~~~~^
GG/src/Texture.cpp:291:5: error: expected expression
GG/src/Texture.cpp:286:70: note: expanded from macro 'IF_IMAGE_TYPE_IS'
            const_view(image._dynamic_cast<image_prefix ## _image_t>())); \
                                                                     ^
GG/src/Texture.cpp:292:10: error: no member named 'current_type_is' in
      'boost::gil::any_image<boost::mpl::vector4<boost::gil::image<boost::gil::pixel<unsigned char,
      boost::gil::layout<boost::mpl::vector1<boost::gil::gray_color_t>, boost::mpl::range_c<int, 0, 1> > >, false,
      std::__1::allocator<unsigned char> >, boost::gil::image<boost::gil::pixel<unsigned char,
      boost::gil::layout<boost::mpl::vector2<boost::gil::gray_color_t, boost::gil::alpha_t>,
      boost::mpl::range_c<int, 0, 2> > >, false, std::__1::allocator<unsigned char> >,
      boost::gil::image<boost::gil::pixel<unsigned char, boost::gil::layout<boost::mpl::vector3<boost::gil::red_t,
      boost::gil::green_t, boost::gil::blue_t>, boost::mpl::range_c<int, 0, 3> > >, false,
      std::__1::allocator<unsigned char> >, boost::gil::image<boost::gil::pixel<unsigned char,
      boost::gil::layout<boost::mpl::vector4<boost::gil::red_t, boost::gil::green_t, boost::gil::blue_t,
      boost::gil::alpha_t>, boost::mpl::range_c<int, 0, 4> > >, false, std::__1::allocator<unsigned char> > > >'
    else IF_IMAGE_TYPE_IS(gil::gray_alpha8)
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
GG/src/Texture.cpp:283:15: note: expanded from macro 'IF_IMAGE_TYPE_IS'
    if (image.current_type_is<image_prefix ## _image_t>()) {            \
        ~~~~~ ^
GG/src/Texture.cpp:292:10: error: expected '(' for function-style cast or type construction
    else IF_IMAGE_TYPE_IS(gil::gray_alpha8)
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
GG/src/Texture.cpp:283:55: note: expanded from macro 'IF_IMAGE_TYPE_IS'
    if (image.current_type_is<image_prefix ## _image_t>()) {            \
                              ~~~~~~~~~~~~~~~~~~~~~~~~^
GG/src/Texture.cpp:292:10: error: expected expression
GG/src/Texture.cpp:283:57: note: expanded from macro 'IF_IMAGE_TYPE_IS'
    if (image.current_type_is<image_prefix ## _image_t>()) {            \
                                                        ^
GG/src/Texture.cpp:292:10: error: no member named '_dynamic_cast' in
      'boost::gil::any_image<boost::mpl::vector4<boost::gil::image<boost::gil::pixel<unsigned char,
      boost::gil::layout<boost::mpl::vector1<boost::gil::gray_color_t>, boost::mpl::range_c<int, 0, 1> > >, false,
      std::__1::allocator<unsigned char> >, boost::gil::image<boost::gil::pixel<unsigned char,
      boost::gil::layout<boost::mpl::vector2<boost::gil::gray_color_t, boost::gil::alpha_t>,
      boost::mpl::range_c<int, 0, 2> > >, false, std::__1::allocator<unsigned char> >,
      boost::gil::image<boost::gil::pixel<unsigned char, boost::gil::layout<boost::mpl::vector3<boost::gil::red_t,
      boost::gil::green_t, boost::gil::blue_t>, boost::mpl::range_c<int, 0, 3> > >, false,
      std::__1::allocator<unsigned char> >, boost::gil::image<boost::gil::pixel<unsigned char,
      boost::gil::layout<boost::mpl::vector4<boost::gil::red_t, boost::gil::green_t, boost::gil::blue_t,
      boost::gil::alpha_t>, boost::mpl::range_c<int, 0, 4> > >, false, std::__1::allocator<unsigned char> > > >'
    else IF_IMAGE_TYPE_IS(gil::gray_alpha8)
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
GG/src/Texture.cpp:286:30: note: expanded from macro 'IF_IMAGE_TYPE_IS'
            const_view(image._dynamic_cast<image_prefix ## _image_t>())); \
                       ~~~~~ ^
GG/src/Texture.cpp:292:10: error: expected '(' for function-style cast or type construction
    else IF_IMAGE_TYPE_IS(gil::gray_alpha8)
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
GG/src/Texture.cpp:286:68: note: expanded from macro 'IF_IMAGE_TYPE_IS'
            const_view(image._dynamic_cast<image_prefix ## _image_t>())); \
                                           ~~~~~~~~~~~~~~~~~~~~~~~~^
GG/src/Texture.cpp:292:10: error: expected expression
GG/src/Texture.cpp:286:70: note: expanded from macro 'IF_IMAGE_TYPE_IS'
            const_view(image._dynamic_cast<image_prefix ## _image_t>())); \
                                                                     ^
GG/src/Texture.cpp:293:10: error: no member named 'current_type_is' in
      'boost::gil::any_image<boost::mpl::vector4<boost::gil::image<boost::gil::pixel<unsigned char,
      boost::gil::layout<boost::mpl::vector1<boost::gil::gray_color_t>, boost::mpl::range_c<int, 0, 1> > >, false,
      std::__1::allocator<unsigned char> >, boost::gil::image<boost::gil::pixel<unsigned char,
      boost::gil::layout<boost::mpl::vector2<boost::gil::gray_color_t, boost::gil::alpha_t>,
      boost::mpl::range_c<int, 0, 2> > >, false, std::__1::allocator<unsigned char> >,
      boost::gil::image<boost::gil::pixel<unsigned char, boost::gil::layout<boost::mpl::vector3<boost::gil::red_t,
      boost::gil::green_t, boost::gil::blue_t>, boost::mpl::range_c<int, 0, 3> > >, false,
      std::__1::allocator<unsigned char> >, boost::gil::image<boost::gil::pixel<unsigned char,
      boost::gil::layout<boost::mpl::vector4<boost::gil::red_t, boost::gil::green_t, boost::gil::blue_t,
      boost::gil::alpha_t>, boost::mpl::range_c<int, 0, 4> > >, false, std::__1::allocator<unsigned char> > > >'
    else IF_IMAGE_TYPE_IS(gil::rgb8)
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
GG/src/Texture.cpp:283:15: note: expanded from macro 'IF_IMAGE_TYPE_IS'
    if (image.current_type_is<image_prefix ## _image_t>()) {            \
        ~~~~~ ^
GG/src/Texture.cpp:293:10: error: expected '(' for function-style cast or type construction
    else IF_IMAGE_TYPE_IS(gil::rgb8)
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
GG/src/Texture.cpp:283:55: note: expanded from macro 'IF_IMAGE_TYPE_IS'
    if (image.current_type_is<image_prefix ## _image_t>()) {            \
                              ~~~~~~~~~~~~~~~~~~~~~~~~^
GG/src/Texture.cpp:293:10: error: expected expression
GG/src/Texture.cpp:283:57: note: expanded from macro 'IF_IMAGE_TYPE_IS'
    if (image.current_type_is<image_prefix ## _image_t>()) {            \
                                                        ^
GG/src/Texture.cpp:293:10: error: no member named '_dynamic_cast' in
      'boost::gil::any_image<boost::mpl::vector4<boost::gil::image<boost::gil::pixel<unsigned char,
      boost::gil::layout<boost::mpl::vector1<boost::gil::gray_color_t>, boost::mpl::range_c<int, 0, 1> > >, false,
      std::__1::allocator<unsigned char> >, boost::gil::image<boost::gil::pixel<unsigned char,
      boost::gil::layout<boost::mpl::vector2<boost::gil::gray_color_t, boost::gil::alpha_t>,
      boost::mpl::range_c<int, 0, 2> > >, false, std::__1::allocator<unsigned char> >,
      boost::gil::image<boost::gil::pixel<unsigned char, boost::gil::layout<boost::mpl::vector3<boost::gil::red_t,
      boost::gil::green_t, boost::gil::blue_t>, boost::mpl::range_c<int, 0, 3> > >, false,
      std::__1::allocator<unsigned char> >, boost::gil::image<boost::gil::pixel<unsigned char,
      boost::gil::layout<boost::mpl::vector4<boost::gil::red_t, boost::gil::green_t, boost::gil::blue_t,
      boost::gil::alpha_t>, boost::mpl::range_c<int, 0, 4> > >, false, std::__1::allocator<unsigned char> > > >'
    else IF_IMAGE_TYPE_IS(gil::rgb8)
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
GG/src/Texture.cpp:286:30: note: expanded from macro 'IF_IMAGE_TYPE_IS'
            const_view(image._dynamic_cast<image_prefix ## _image_t>())); \
                       ~~~~~ ^
GG/src/Texture.cpp:293:10: error: expected '(' for function-style cast or type construction
    else IF_IMAGE_TYPE_IS(gil::rgb8)
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
GG/src/Texture.cpp:286:68: note: expanded from macro 'IF_IMAGE_TYPE_IS'
            const_view(image._dynamic_cast<image_prefix ## _image_t>())); \
                                           ~~~~~~~~~~~~~~~~~~~~~~~~^
GG/src/Texture.cpp:293:10: error: expected expression
GG/src/Texture.cpp:286:70: note: expanded from macro 'IF_IMAGE_TYPE_IS'
            const_view(image._dynamic_cast<image_prefix ## _image_t>())); \
                                                                     ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
```

**Comment by jbeich** [comment]
> Apparently `basic_socket_acceptor` has an extra template parameter in Boost 1.70

Likely caused by https://github.com/boostorg/asio/commit/59066d80b26e

**Comment by geoffthemedio** [comment]
Can I get an updated error log with https://github.com/freeorion/freeorion/pull/2410 ?

**Comment by jbeich** [comment]
[Error log](https://github.com/freeorion/freeorion/files/3002885/freeorion-s20190324.log):
```c++
GG/src/Texture.cpp:304:5: error: value of type 'boost::gil::image<boost::gil::pixel<unsigned char, boost::gil::layout<boost::mpl::vector1<boost::gil::gray_color_t>, boost::mpl::range_c<int, 0, 1> > >, false, std::__1::allocator<unsigned char> >' is not contextually convertible to 'bool'
    IF_IMAGE_TYPE_IS(gil::gray8)
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
GG/src/Texture.cpp:288:9: note: expanded from macro 'IF_IMAGE_TYPE_IS'
    if (boost::get<image_prefix ## _image_t>(image)) {                  \
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
GG/src/Texture.cpp:305:10: error: value of type 'boost::gil::image<boost::gil::pixel<unsigned char, boost::gil::layout<boost::mpl::vector2<boost::gil::gray_color_t, boost::gil::alpha_t>, boost::mpl::range_c<int, 0, 2> > >, false, std::__1::allocator<unsigned char> >' is not contextually convertible to 'bool'
    else IF_IMAGE_TYPE_IS(gil::gray_alpha8)
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
GG/src/Texture.cpp:288:9: note: expanded from macro 'IF_IMAGE_TYPE_IS'
    if (boost::get<image_prefix ## _image_t>(image)) {                  \
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
GG/src/Texture.cpp:306:10: error: value of type 'boost::gil::image<boost::gil::pixel<unsigned char, boost::gil::layout<boost::mpl::vector3<boost::gil::red_t, boost::gil::green_t, boost::gil::blue_t>, boost::mpl::range_c<int, 0, 3> > >, false, std::__1::allocator<unsigned char> >' is not contextually convertible to 'bool'
    else IF_IMAGE_TYPE_IS(gil::rgb8)
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
GG/src/Texture.cpp:288:9: note: expanded from macro 'IF_IMAGE_TYPE_IS'
    if (boost::get<image_prefix ## _image_t>(image)) {                  \
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
GG/src/Texture.cpp:307:10: error: value of type 'boost::gil::image<boost::gil::pixel<unsigned char, boost::gil::layout<boost::mpl::vector4<boost::gil::red_t, boost::gil::green_t, boost::gil::blue_t, boost::gil::alpha_t>, boost::mpl::range_c<int, 0, 4> > >, false, std::__1::allocator<unsigned char> >' is not contextually convertible to 'bool'
    else IF_IMAGE_TYPE_IS(gil::rgba8)
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
GG/src/Texture.cpp:288:9: note: expanded from macro 'IF_IMAGE_TYPE_IS'
    if (boost::get<image_prefix ## _image_t>(image)) {                  \
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
4 errors generated.
```

**Comment by geoffthemedio** [comment]
now?

**Comment by jbeich** [comment]
[Builds fine](https://github.com/freeorion/freeorion/files/3013524/freeorion-s20190326.log)

**Comment by geoffthemedio** [comment]
And runs?

**Comment by jbeich** [comment]
I don't use/play FreeOrion, so have no clue about how it worked (or supposed to work) before. Quick Start on FreeBSD 11.2 amd64 (clang 6.0) and 13.0 (clang 8.0) worked fine. In Multi Player trying to host a game leads to "Timed out while attempting to connect to server" but this maybe because I've disabled IPv6 in kernel config.

**Comment by jbeich** [comment]
If you need something more than crashtest then asking downstream package maintainer (e.g., @amdmi3 for FreeBSD) maybe better. I'm simply helping out with Boost updates.

**Comment by geoffthemedio** [comment]
I mainly wanted to know if it gets to the intro screen menu and displays the background splash image and FreeOrion logo.
