### ISSUE TITLE
failing to build with Boost 1.76

### ISSUE THREAD

**Issue by brad0** [freeorion/freeorion#3464]
freeorion is failing to build with Boost 1.76. Currently we're (OpenBSD) using Boost 1.73 and it builds fine.

```
/home/ports/pobj/freeorion-0.4.10.1/bin/c++ -DBINPATH=\"/usr/local/bin\" -DBOOST_ALL_DYN_LINK -DENABLE_BINRELOC -DFREEORION_BUILD_HUMAN -DFREEORION_OPENBSD -DGiGiHeader -DSHAREPATH=\"/usr/local/share\" -I/home/ports/pobj/freeorion-0.4.10.1/src-tarball/GG/Boost::boost -I/home/ports/pobj/freeorion-0.4.10.1/src-tarball/GG -isystem /usr/X11R6/include -isystem /usr/local/include/AL -isystem /usr/local/include/ogg -isystem /usr/local/include/vorbis -isystem /usr/X11R6/include/freetype2 -isystem /usr/local/include -O2 -pipe -DNDEBUG -fvisibility=hidden -Wall -std=c++14 -MD -MT CMakeFiles/freeorion.dir/UI/CombatReport/GraphicalSummary.cpp.o -MF CMakeFiles/freeorion.dir/UI/CombatReport/GraphicalSummary.cpp.o.d -o CMakeFiles/freeorion.dir/UI/CombatReport/GraphicalSummary.cpp.o -c /home/ports/pobj/freeorion-0.4.10.1/src-tarball/UI/CombatReport/GraphicalSummary.cpp
/home/ports/pobj/freeorion-0.4.10.1/src-tarball/UI/CombatReport/GraphicalSummary.cpp:449:32: error: no member named 'math' in namespace 'boost'
            handle.y -= boost::math::sign(Value(direction.y))*GG::Y(head_width);
                        ~~~~~~~^
/home/ports/pobj/freeorion-0.4.10.1/src-tarball/UI/CombatReport/GraphicalSummary.cpp:455:32: error: no member named 'math' in namespace 'boost'
            handle.x -= boost::math::sign(Value(direction.x)) * GG::X(head_width);
                        ~~~~~~~^
2 errors generated.
```

**Comment by geoffthemedio** [comment]
I don't see a relevant change, but the offending function is simple enough to replace...

Does
````
 UI/CombatReport/GraphicalSummary.cpp | 13 ++++++++-----
 1 file changed, 8 insertions(+), 5 deletions(-)

diff --git a/UI/CombatReport/GraphicalSummary.cpp b/UI/CombatReport/GraphicalSummary.cpp
index e2fc7fb1a..10e8869fe 100644
--- a/UI/CombatReport/GraphicalSummary.cpp
+++ b/UI/CombatReport/GraphicalSummary.cpp
@@ -340,6 +340,11 @@ private:
     GG::Clr m_health_color;
 };
 
+namespace {
+    inline int sign(int z)
+    { return (z == 0) ? 0 : (z < 0) ? -1 : 1; }
+}
+
 /// A Bar that shows the aggregate health of a side,
 /// and the statuses of all its units
 class SideBar : public GG::Wnd {
@@ -449,13 +452,13 @@ public:
         } else if (direction.x == 0) {
             // Vertical arrow
             handle = end;
-            handle.y -= boost::math::sign(Value(direction.y))*GG::Y(head_width);
+            handle.y -= sign(Value(direction.y))*GG::Y(head_width);
             delta_x = GG::X(head_width);
             delta_y = GG::Y0;
         } else {
             //horizontal arrow
             handle = end;
-            handle.x -= boost::math::sign(Value(direction.x)) * GG::X(head_width);
+            handle.x -= sign(Value(direction.x)) * GG::X(head_width);
             delta_x = GG::X0;
             delta_y = GG::Y(head_width);
         }
````
fix it?

**Comment by brad0** [comment]
That builds fine. Thank you.

**Comment by geoffthemedio** [comment]
I'll probably just remove the whole function, as I can't actually see what it's supposed to be drawing...

**Comment by brad0** [comment]
Sure, whatever gets the end result of having it build Ok.

**Comment by geoffthemedio** [comment]
should be fixed by https://github.com/freeorion/freeorion/commit/9cc1926e8126163d3b8877c0112e11c462a96384
