### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by Grummel7** [freeorion/freeorion#4671]
Current master does not compile in my enviroment (g++ (Debian 10.2.1-6) 10.2.1 20210110)

```
[  0%] Building CXX object CMakeFiles/freeorioncommon.dir/util/StringTable.cpp.o
(lots of warnings skipped)
...
util/StringTable.cpp:312:48: error: no match for ‘operator|’ (operand types are ‘boost::unordered::unordered_map<std::__cxx11::basic_string<char>, std::__cxx11::basic_string<char>, StringTable::hasher, StringTable::equalizer>’ and ‘const std::ranges::views::__adaptor::_RangeAdaptorClosure<<lambda(_Range&&)> >’)
  312 |         for (auto& user_read_entry : m_strings | range_values) {
      |                                      ~~~~~~~~~ ^ ~~~~~~~~~~~~
      |                                      |           |
      |                                      |           const std::ranges::views::__adaptor::_RangeAdaptorClosure<<lambda(_Range&&)> >
      |                                      boost::unordered::unordered_map<std::__cxx11::basic_string<char>, std::__cxx11::basic_string<char>, StringTable::hasher, StringTable::equalizer>
In file included from /usr/include/c++/10/bits/ranges_algobase.h:38,
                 from /usr/include/c++/10/bits/ranges_uninitialized.h:36,
                 from /usr/include/c++/10/memory:69,
                 from /usr/include/boost/container_hash/extensions.hpp:35,
                 from /usr/include/boost/container_hash/hash.hpp:761,
                 from /usr/include/boost/functional/hash.hpp:6,
                 from /usr/include/boost/unordered/unordered_map.hpp:18,
                 from /usr/include/boost/unordered_map.hpp:17,
                 from /home/muzz/freeorion-project/Grummel7/util/StringTable.h:7,
                 from /home/muzz/freeorion-project/Grummel7/util/StringTable.cpp:1:
```

**Comment by o01eg** [comment]
Which python and boost version you have on Debian 10? Packages info shows me 3.7 and 1.67 while master requires 3.9 and 1.73.

**Comment by Grummel7** [comment]
Python is 3.9.2
boost-dev packages are 1.74

The compiler output was confusing, I am actually on Debian 11.7, only the compiler hasn't been updated for a while.

**Comment by o01eg** [comment]
I suppose it's a compiler issue. CI with Debian Stable successfully builds code.

**Comment by geoffthemedio** [comment]
It's likely a compiler issue. It has the `<ranges>` header, but hasn't implemented it fully. Boost version likely doesn't matter, as it's using the C++ standard library range adaptor that isn't working. You could try adding an additional compiler version check [here](https://github.com/freeorion/freeorion/blob/master/util/ranges.h#L4) to force it to use the Boost implementation instead.

Edit: probly could require GCC >= 11 to use the standard library range adaoptors, but I  can't easily test that right now.

**Comment by o01eg** [comment]
Yes, it fails on Debian oldstable https://github.com/freeorion/freeorion/actions/runs/5819038656/job/15776658076

**Comment by geoffthemedio** [comment]
https://godbolt.org/z/E38ennGGM

works on gcc 10.4 but not 10.3

**Comment by Grummel7** [comment]
> Yes, it fails on Debian oldstable https://github.com/freeorion/freeorion/actions/runs/5819038656/job/15776658076

Strange, I thought had set my system to update to stable, but I found it was actually updating to bullseye all the time. Now I updated to stable and have g++-12.
