### PR TITLE
Supply Reworking

### PR DESCRIPTION
**Pull request by geoffthemedio**
Reworks supply propegation so that any system is only supplied by at most one empire, and one empire's supply can push back another's, depending on their supply ranges at the source systems.

Needs Python / AI input on how to rework the CalculateSupplyUpdate and supplyProjectionsP functions in EmpireWrapper, as these appeared to use a slightly modified version of the old supply propegation to calculate how far, in jumps, a system was from a fleet-supplyable system for an empire, but the new supply calculation doesn't really make sense to use in that way. A simple calculation of jump distance to a supplyable system could be implemented if needed.

### CODE REVIEW

**Comment by geoffthemedio** [comment]
reworked_supply_propegation_map

Still has some quirks with which lanes are fully / partly coloured for each empire.

**Comment by Vezzra** [comment]
Looks good on a first glance.

Can you open a thread in the Design section with a brief, but still bit more detailed explanation on how the new mechanic works? Although I probably can guess the essentials from your short description above, I don't want to provide feedback on assumptions, and there's at least one thing which isn't clear to me.

As Supply is a key mechanic and you've already provided an implementation here, I suggest opening that thread on the Top Priority Game Design forum. That has worked well for the Fighter&Carrier stuff, so I think we can do that in this case again.

**Comment by MatGB** [comment]
Can't compile:

```
[ 97%] Building CXX object client/human/CMakeFiles/freeorion.dir/__/__/UI/TextBrowseWnd.cpp.o
Linking CXX executable ../../freeorion
CMakeFiles/freeorion.dir/__/__/UI/MapWnd.cpp.o: In function `MapWnd::RenderSystems()':
MapWnd.cpp:(.text+0x5c25): undefined reference to `SupplyManager::EmpireThatCanSupplyAt(int) const'
CMakeFiles/freeorion.dir/__/__/UI/MapWnd.cpp.o: In function `(anonymous namespace)::GetNearestSupplyPoint(Empire const*, int)':
MapWnd.cpp:(.text+0x9333): undefined reference to `SupplyManager::FleetSupplyableSystemIDs(int) const'
CMakeFiles/freeorion.dir/__/__/UI/MapWnd.cpp.o: In function `MapWnd::DispatchFleetsExploring()':
MapWnd.cpp:(.text+0xd1c3): undefined reference to `SupplyManager::FleetSupplyableSystemIDs(int) const'
CMakeFiles/freeorion.dir/__/__/UI/MapWnd.cpp.o: In function `MapWnd::InitStarlaneRenderingBuffers()':
MapWnd.cpp:(.text+0xeeb0): undefined reference to `SupplyManager::ResourceSupplyGroups(int) const'
MapWnd.cpp:(.text+0xf0c4): undefined reference to `SupplyManager::SupplyStarlaneTraversals(int) const'
MapWnd.cpp:(.text+0xff87): undefined reference to `SupplyManager::SupplyStarlaneTraversals(int) const'
MapWnd.cpp:(.text+0x10400): undefined reference to `SupplyManager::SupplyObstructedStarlaneTraversals(int) const'
CMakeFiles/freeorion.dir/__/ClientApp.cpp.o: In function `ClientApp::ClientApp()':
ClientApp.cpp:(.text+0xc98): undefined reference to `SupplyManager::SupplyManager()'
../../libfreeorioncommon.so: undefined reference to `SupplyManager::SystemHasFleetSupply(int, int) const'
../../libfreeorioncommon.so: undefined reference to `SupplyManager::FleetSupplyableSystemIDs() const'
collect2: error: ld returned 1 exit status
make[2]: *** [freeorion] Error 1
make[1]: *** [client/human/CMakeFiles/freeorion.dir/all] Error 2
make: *** [all] Error 2
```
- edit by Cjkjvfnby: formatting

**Comment by Vezzra** [comment]
The cmake files hadn't been updated, and I also had to add an additional `#include` to `Supply.h` to get the branch to build on Linux. I've just committed those fixes to the branch a few minutes ago, pls try again.

**Comment by MatGB** [comment]
Yup, compiled and now runs, thanks.

**Comment by Vezzra** [comment]
There's another issue that has been introduced by commit 2e3604c5dd5815e65b46c2c467deddd28b09c59c in master (merge of PR #472), which more or less breaks the AI. I've committed a fix to master (6ea1e1fa157abb0eb0e7c727fc8e774e830f84ea), but the branch of this PR needs to be rebased to incorporate the fix.

As that's quite essential for effective testing, this should be done ASAP. @geoffthemedio, if you want, I can do that, or do you want to do it yourself?

**Comment by geoffthemedio** [comment]
go ahead

**Comment by Vezzra** [comment]
Done.

**Comment by MatGB** [comment]
supply-branch-production

Production doesn't seem to propagate properly, making colonising-via-building impossible. It knows it's in supply for queuing the building but resources aren't being spread between systems properly, the system on the left is from the original ship and I just switched it to produce, the one on the right is an outpost that should be making me a colony building.

**Comment by MatGB** [comment]
Not even sharing it between planets in the same system, I put a colony down on the deser world in Rukbat Beta but the colony building on the terran world is still showing Never after a few turns and the starlanes are showing wasted production.

**Comment by MatGB** [comment]
refuel-propagation
It's also not extending to the full reach, the ship highlighted is two jumps away from Rukbat delta which has a supply of 2, but isn't being refueled (and the system isn't circled to show it's in supply). I had earlier deliberately reduced the cost of Orbital Construction in order to extend supply a bit to see if that helps but it doesn't.

Game is basically unplayable with both these problems ergo I'm switching to a different project to test, hope these can be sorted.

**Comment by geoffthemedio** [comment]
Which is "the system" that isn't circled? If you mean the one with the selected fleet (and not the selected system), what's under the FleetWnd?

**Comment by MatGB** [comment]
There's a monster in the next system over blocking supply, and yes, the one with the fleet in, that fleet should be in supply and refueled as it's two jumps away from a home system and there's no competition for that system (I'm blocked in by Sentinels so I'd have to restart anyway).

It's my understanding that Sentries should block propagation up to and beyond their location, but not block it in systems they're not in.

**Comment by geoffthemedio** [comment]
fixed?

**Comment by MatGB** [comment]
supply-branch-propagation
Um, sort of, at least for the control of endpoint systems. Screenshot shows gray line where it should be purple in between two systems of mine.

Plus, production still not being shared outside of individual planets, can't build gas giant generators, etc. and everywhere with any production needs a shipyard for it to be usable.

**Comment by geoffthemedio** [comment]
Do you mean the system under the ion storm? Probably that monster is in it, blocking the supply propegation.

Production sharing between systems seems to work for me...

production_sharing

**Comment by MatGB** [comment]
All systems, production isn't being shared between individual planets in the same system let alone empire wide, having to work out which planet isn't using its pp in the same system isn't good. See my first screenshot, I've spread out using ships and colony bases but nothing's being shared.

**Comment by geoffthemedio** [comment]
You can't replicate my last screenshot? (With production being shared between two adjacent systems...)

**Comment by MatGB** [comment]
No, not at all, that's not been working since I first compiled it.

**Comment by geoffthemedio** [comment]
Double-check updating, and rebuild the server fresh? The revision number in your screenshot doesn't appear to match any of the commits I see listed here...

**Comment by MatGB** [comment]
That's a single commit of mine to test some stuff and make the game playable (I changed orbital generation and supply distances within script).

It wasn't working on initial build, but to confirm I'll make a completely new branch and compile again.

**Comment by geoffthemedio** [comment]
Depending when "on initial build" was, that makes sense, as I forgot to update the industry resource pool with the groups of supply-connected systems. But that was fixed in https://github.com/freeorion/freeorion/commit/35faab21ea113474713474947c792a5b945072c5 .

**Comment by MatGB** [comment]
Ah, yes, for some reason when I cherry picked Vezzra's commit's they got a new hash, my initial build was immediately after his.

OK, appears things are now working as intended so I can test the actual point.

**Comment by geoffthemedio** [comment]
Double check if there are two planets with zero supply range in supply-isolated system, whether they can / should be able to share resources with eachother.

Also, the cross-lanes between systems sometimes aren't coloured when they weren't necessary for supply propegation. Will hopefully fix with a post-processing reworking of the determination of traversals, but it's cosmetic, so can wait, I think.

**Comment by MatGB** [comment]
Currently I have two entirely separate resource groups that're sharing together but are split where they shouldn't be, I shall test the other when I get the chance.

**Comment by geoffthemedio** [comment]
Could you elaborate on what that means / illustrate?

**Comment by MatGB** [comment]
Screenshot above (this one)supply-branch-propagation

Multiple turns later I've colonised Axis alpha, that's linked by supply to Ragnarok but the grey line is still there, and the Rukbat cluster isn't linked out to the other group, nor is it getting the solar generator or industrial centre bonuses from Ragnarok, there's nothing blocking the systems and they were linked but not sharing before #77e4583

**Comment by MatGB** [comment]
OK, weirder, I set Rukbat delta to Logistics and the gap moved
supply-branch-logistics

Overlap within supply cancels link somehow?

**Comment by Vezzra** [comment]
Test game on OSX, turn 5, a colony ship just arrived at Lyot Beta and has been ordered to colonize Lyot Beta VII. As you can see, Lyot Beta is supply connected to the capitol at Tabul Alpha:

supplyturn05

Turn 6, Lyot Beta VII has been colonized, and now the supply link between Tabul Alpha and Lyot Beta has been broken. To be precise, the connection between Lyot Alpha and Lyot Beta is gone. It's not just a display glitch, the Outpost Base enqueued at Lyot Beta VII doesn't get any PP:

supplyturn06

**Comment by MatGB** [comment]
Yeah, I got some weirdness, I set Axis to logistics and took Rukbat delta off, first it linked up to Ragnarok, then that link was broken but it linked to Rukbat, then both links were broken. It's as if they're competing with each other.

**Comment by Vezzra** [comment]
Yep, that would make sense with my test game too. As soon as Lyot Beta VII has been colonized, there was a "competing" supply source with supply range 1. Tabul Alpha is a supply source with range 2, which means Lyot Alpha gets connected with Tabul Alpha, but not with Lyot Beta.

Apparently supply sources of the same empire compete with each other. The reason why supply sharing between the systems in Geoffs test game worked might be that, being adjacent to each other, the one system might have had sufficient supply range advantage that it overpowered the other system, so supply worked...?

**Comment by geoffthemedio** [comment]
There is code specifically intended to prevent that, but apparently it's not working, or is being overwritten somehow...

**Comment by geoffthemedio** [comment]
Still problems with extra traversals being recorded, but I think the connection fighting within an empire is fixed...

Although it seems to be propegating into enemy systems with planets even when they have an armed ship there (but not into planetless systems...)...

**Comment by MatGB** [comment]
Shall test, curious, was mimium_range_to_spread meant to be minimum_r... and if so could that have been an issue?

**Comment by geoffthemedio** [comment]
The variable name had a typo. It was used consistently though, or else it would have caused compile errors.

**Comment by MatGB** [comment]
Fair, still learning the basics of reading C code.

Appears to now be working, but not 100% sure as I've been building Space Elevators at key points to override.

**Comment by TheSilentOne1** [comment]
supply-rework
Interesting! Not sure everything is working as intended yet though, see screenshot:
- Berkano Egassem has 3 supply, but there's no red circle around Londinium
- Sarma is freshly conquered and has 0 supply, but connects to Leera (but has no circle either)?
  (build 44c8ffd)

**Comment by geoffthemedio** [comment]
The line to non-circles systems are the "problems with extra traversals being recorded" I mentioned...

**Comment by TheSilentOne1** [comment]
Sorry, I wasn't able to figure out what that meant... ;)

**Comment by Vezzra** [comment]
Yep, seems to work now. However, as expected, the AI is broken, it's not colonizing at all.

AI team: any idea/estimates how complicated it will be to adjust the AI to these changes?

**Comment by geoffthemedio** [comment]
The AI might not need any adjustment, as long as the function it was using is re-implemented. As far as I could tell, it was just using supply propegation into negative values to figure out how far systems were from a supplied system. This could be implemented again if that's all that's needed, except not using the new supply propegation mechanics, but rather a simple old-style supply spreading mechanism.

**Comment by Vezzra** [comment]
Ok, anyone of the AI team up to this (besides @Dilvish-fo, who isn't available ATM)? @Cjkjvfnby doesn't do C++ coding, @Morlic-fo maybe...?

**Comment by geoffthemedio** [comment]
I can do the C++, as long as I know what information the AI actually needs / expects...

**Comment by MatGB** [comment]
IIRC CJ can't/doesn't compile and works on Windows, I suspect he'd need a working exe to make the important changes.

**Comment by Morlic-fo** [comment]
> As far as I could tell, it was just using supply propegation into negative values to figure out how far systems were from a supplied system. This could be implemented again if that's all that's needed

Reimplementing this should probably do the trick as far as the "broken" part of the AI is concerned. Obviously eventually adjustments are needed so it utilizes the new mechanics as well.

**Comment by Cjkjvfnby** [comment]
I will look into supply next week.

**Q:**  Do two systems that connected by supplies and does not connected to capital share production?

At current point I see 2 items in API related to supply (**master 746cb85**):
`empire.supplyUnobstructedSystems`  return set of ids that have supply connection to capital.

 `empire.supplyProjections(min_tracked_supply, obstructed)`
Returns map of `sys_id`, `supply value`.     I don`t know yet what is this value means.

I try this code:

``` python
    u = fo.getUniverse()
    e = fo.getEmpire()
    supplied = {x: '+' for x in e.supplyUnobstructedSystems}
    proj_negative = e.supplyProjections(-1, False)
    proj_zero = e.supplyProjections(0, False)
    proj_one = e.supplyProjections(1, False)

    superkeys = set(supplied)
    superkeys.update(proj_negative)
    superkeys.update(proj_zero)
    superkeys.update(proj_one)

    print "Supply survey at turn", fo.currentTurn()
    print 'ID  Sup -1  0  1 system'
    for key in superkeys:
        print '%-3s %3s %3s %3s %3s %s' % (key,
                                          supplied.get(key, ''),
                                          proj_negative.get(key, ''),
                                          proj_zero.get(key, ''),
                                          proj_one.get(key, ''),
                                          u.getSystem(key).name)
```

And get next output at turn 20. I don't know how to interpret this.

```
ID  Su  -1   0   1 system
  0     -1         Elased β
196      0   0     Gefjon
 11      0   0     Lambda
269  +   2   2   2 Mothallah
206  +   3   3   3 Marinara
145      0   0
345      1   1   1 Elased α
 28  +             Albion α
286  +   0   0     Albion δ
288  +  -1         Albion β
233      1   1   1 Burke
 45     -1         Estela β
305  +   0   0     Goth β
242  +   2   2   2 Alkurhah
179  +   0   0     Siqieiq
310  +   1   1   1 Goth α
120     -1
```

**Comment by geoffthemedio** [comment]
Unobstructed systems have nothing to do with the capital; rather, they are systems that don't have anything in them that blocks suppy propegation.

supplyProjections in the Python API returns something like the largest value for the empire of system supply range minus distance to the system from the requested location. This is calculated into negative numbers, which is used to estimate how many starlane jumps a system is away from a source of supply.

**Comment by Vezzra** [comment]
Um, @Cjkjvfnby, did you by any chance edit @geoffthemedio's comment above instead of creating a new one and quoting him?

**Comment by Cjkjvfnby** [comment]
> Unobstructed systems have nothing to do with the capital; rather, they are systems that don't have anything in them that blocks suppy propegation.
- `Alkurhah` have supply range 2 and no enemy fleets in 2 jumps it is in set
- `Goth β` supply is 0 (no colonies) and have no enemy in it
- something blocks `Burke` supply and it is not in set

What is about `Albion α`?

> supplyProjections in the Python API returns something like the largest value for the empire of system supply range minus distance to the system from the requested location. This is calculated into negative numbers, which is used to estimate how many starlane jumps a system is away from a source of supply.

Thank you for explanation.

**Comment by Cjkjvfnby** [comment]
@Vezzra oops, fixed.

**Comment by geoffthemedio** [comment]
I don't know / understand what you're asking, or how to interpret your chart, or have any way to refer to information not in the chart.

**Comment by Cjkjvfnby** [comment]
> I don't know / understand what you're asking, or how to interpret your chart, or have any way to refer to information not in the chart.

I will think how to ask that in different way. 

I still have question about game mechanic:
How production and research work in case when we have two clusters separated from each other?
There is list of systems with colonies in each cluster:
- first cluster: `homeword`, `sys1`
- second cluster `sys2`, `sys3`

Research of `homeword` and `sys1` are combined and used.  Research for `sys2` and `sys3` are wasted.
Production of `sys1` can be used as `homeword`. 
**Question**:  can `sys2` use production of `sys3`?

**Comment by MatGB** [comment]
Research should be fully shared. Production should share within each cluster (there was a bug where that wasn't happening but it was fixed).

So yes.

**Comment by Cjkjvfnby** [comment]
I found situation that I did not understand:
System is unobstructed, cannot supply fleet and have no colonies. It have value 2 in supplyProjections(1, False) but not present in supplyProjections(1, True).   

Looks like we have different approach to calculation of unobstructed systems or I did not get something.  

PS `supplyProjections(<size>, True)`  is not used in code.

**Comment by geoffthemedio** [comment]
another obstructed system can block supply propegation into an unobstructed system if it's between it and the source of supply.

**Comment by geoffthemedio** [comment]
I reimplemented supplyProjections to return 0 for systems in supply, and the negative of the number of jumps to the nearest supplied systems otherwise.

Additional testing requested to see if that fixed the "broken" AI issues...

**Comment by Vezzra** [comment]
Build and runs ok on OSX and Linux. AI seems to be able to colonize and expand again. I guess the AI will still need adjustments to better cope with the changed mechanics, but it seems to handle things already well enough.

IMO ok to merge.
