### PR TITLE
Replace deprecated boost::asio stuff.

### LINKED ISSUE #2409: Fails to build with Boost 1.70 (Beta1)
Regressed by boostorg/asio@a72fbb0b867f:
```c++
network/ServerNetworking.cpp:691:42: error: no member named 'get_io_service' in
      'boost::asio::basic_socket_acceptor<boost::asio::ip::tcp, boost::asio::executor>'
            m_player_connection_acceptor.get_io_service(),
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
1 error generated.
```

### PR DESCRIPTION
**Pull request by geoffthemedio**
Hopefully resolves https://github.com/freeorion/freeorion/issues/2409

### CODE REVIEW

**Comment by o01eg** [comment]
Could it be backported to 0.4.8 branch and published as a bug-fix release?

**Comment by geoffthemedio** [comment]
Probably
