### ISSUE TITLE
Unowned monsters and planets not shooting

### ISSUE THREAD

**Issue by Oberlus** [freeorion/freeorion#3280]
Bug Report
==========

Environment
-----------
* **FreeOrion Version**: b86e635
* **Operating System**: Windows 8.1
* **Fetched as** 
  * Weekly development build

Description
-----------
Unowned monsters and planets with defenses are not shooting at my ships.
This breaks balance for galaxy settings Monster, Specials and Natives. It's rather gamebreaking.

Check out system Vega alpha in the attached save game.

[monsters_not_shooting.zip](https://github.com/freeorion/freeorion/files/5826992/monsters_not_shooting.zip)

**Comment by Oberlus** [comment]
I loaded the attached save game in current master 08039ef in Ubuntu 18.04. When pressing Turn I get this errors in Messages window:

```
[18 Jan 11:02:44] AI_2: AI_Error: AI script error : FreeOrionAI.py:_error_handler():74  - Exception 'tuple' object has no attribute 'attacks' occurred during generateOrders
Traceback (most recent call last):
  File "/home/lucas/Projects/FreeOrion/freeorion/default/python/AI/FreeOrionAI.py", line 71, in _error_handler
    res = func(*args, **kwargs)
  File "/home/lucas/Projects/FreeOrion/master-testing-build/default/python/common/listeners.py", line 42, in wrapper
    res = funct(*args)
  File "/home/lucas/Projects/FreeOrion/freeorion/default/python/AI/FreeOrionAI.py", line 331, in generateOrders
    aistate.prepare_for_new_turn()
  File "/home/lucas/Projects/FreeOrion/freeorion/default/python/AI/AIstate.py", line 998, in prepare_for_new_turn
    self.__report_last_turn_fleet_missions()
  File "/home/lucas/Projects/FreeOrion/freeorion/default/python/AI/AIstate.py", line 952, in __report_last_turn_fleet_missions
    CombatRatingsAI.get_fleet_rating(fleet_id),
  File "/home/lucas/Projects/FreeOrion/freeorion/default/python/AI/CombatRatingsAI/_ratings.py", line 95, in get_fleet_rating
    return get_fleet_combat_stats(fleet_id, max_stats=False).get_rating(enemy_stats)
  File "/home/lucas/Projects/FreeOrion/freeorion/default/python/AI/CombatRatingsAI/_fleet_combat_stats.py", line 26, in get_rating
    return combine_ratings(x.get_rating(enemy_stats) for x in self._ship_stats)
  File "/home/lucas/Projects/FreeOrion/freeorion/default/python/AI/freeorion_tools/combine_ratings.py", line 48, in combine_ratings
    return reduce(_combine_ratings, chain(first, ratings), 0.0)
  File "/home/lucas/Projects/FreeOrion/freeorion/default/python/AI/CombatRatingsAI/_fleet_combat_stats.py", line 26, in <genexpr>
    return combine_ratings(x.get_rating(enemy_stats) for x in self._ship_stats)
  File "/home/lucas/Projects/FreeOrion/freeorion/default/python/AI/CombatRatingsAI/_ship_combat_stats.py", line 78, in get_rating
    my_hit_points *= self._calculate_shield_factor(enemy_stats.attacks, self.shields)
AttributeError: 'tuple' object has no attribute 'attacks'
Local context: {'my_hit_points': 128.0, 'self': <CombatRatingsAI._ship_combat_stats.ShipCombatStats object at 0x7f7644e09dd8>, 'enemy_stats': (((6.0, 1),), 15, 0, 0, 0, 0, 0, False, 0, False)}

[18 Jan 11:02:44] AI_1: AI_Error: AI script error : FreeOrionAI.py:_error_handler():74  - Exception 'tuple' object has no attribute 'attacks' occurred during generateOrders
Traceback (most recent call last):
  File "/home/lucas/Projects/FreeOrion/freeorion/default/python/AI/FreeOrionAI.py", line 71, in _error_handler
    res = func(*args, **kwargs)
  File "/home/lucas/Projects/FreeOrion/master-testing-build/default/python/common/listeners.py", line 42, in wrapper
    res = funct(*args)
  File "/home/lucas/Projects/FreeOrion/freeorion/default/python/AI/FreeOrionAI.py", line 331, in generateOrders
    aistate.prepare_for_new_turn()
  File "/home/lucas/Projects/FreeOrion/freeorion/default/python/AI/AIstate.py", line 998, in prepare_for_new_turn
    self.__report_last_turn_fleet_missions()
  File "/home/lucas/Projects/FreeOrion/freeorion/default/python/AI/AIstate.py", line 952, in __report_last_turn_fleet_missions
    CombatRatingsAI.get_fleet_rating(fleet_id),
  File "/home/lucas/Projects/FreeOrion/freeorion/default/python/AI/CombatRatingsAI/_ratings.py", line 95, in get_fleet_rating
    return get_fleet_combat_stats(fleet_id, max_stats=False).get_rating(enemy_stats)
  File "/home/lucas/Projects/FreeOrion/freeorion/default/python/AI/CombatRatingsAI/_fleet_combat_stats.py", line 26, in get_rating
    return combine_ratings(x.get_rating(enemy_stats) for x in self._ship_stats)
  File "/home/lucas/Projects/FreeOrion/freeorion/default/python/AI/freeorion_tools/combine_ratings.py", line 48, in combine_ratings
    return reduce(_combine_ratings, chain(first, ratings), 0.0)
  File "/home/lucas/Projects/FreeOrion/freeorion/default/python/AI/CombatRatingsAI/_fleet_combat_stats.py", line 26, in <genexpr>
    return combine_ratings(x.get_rating(enemy_stats) for x in self._ship_stats)
  File "/home/lucas/Projects/FreeOrion/freeorion/default/python/AI/CombatRatingsAI/_ship_combat_stats.py", line 78, in get_rating
    my_hit_points *= self._calculate_shield_factor(enemy_stats.attacks, self.shields)
AttributeError: 'tuple' object has no attribute 'attacks'
Local context: {'my_hit_points': 40.0, 'self': <CombatRatingsAI._ship_combat_stats.ShipCombatStats object at 0x7f112b0f0be0>, 'enemy_stats': (((6.0, 1),), 15, 0, 0, 0, 0, 0, False, 0, False)}
```

**Comment by Oberlus** [comment]
Another save game for latest master 08039ef that does not show AI errors (monsters still not shooting). There are several monster designs, none are attacking any foe.

[FreeOrion_Oberlus_Abyss_0013_20210118_111457.zip](https://github.com/freeorion/freeorion/files/5829484/FreeOrion_Oberlus_Abyss_0013_20210118_111457.zip)

**Comment by Oberlus** [comment]
```
~/Projects/FreeOrion/freeorion$ git bisect good
d091d066c4a5a5f7687964767d1657ade410337a is the first bad commit
```

Culprit is somewhere within d091d06

**Comment by Cjkjvfnby** [comment]
Hi, @Oberlus 

There are 2 unrelated issues: one you mentioned and another is the incompatibility of saves.
Saves were broken by my changes https://github.com/freeorion/freeorion/pull/3278, I will try to fix them asap.  

Fix for savegame loading: https://github.com/freeorion/freeorion/pull/3281

**Comment by Oberlus** [comment]
This bug also affects unowned planets.

@geoffthemedio

> Culprit is somewhere within [d091d06](https://github.com/freeorion/freeorion/commit/d091d066c4a5a5f7687964767d1657ade410337a)

**Comment by agrrr3** [comment]
At least this seems wrong in Conditions.cpp VisibleToEmpireSimpleMatch::operator()
```
           if (!candidate || m_empire_id == ALL_EMPIRES)
                return false;
```

ALL_EMPIRES is used for unowned objects. I removed the `|| m_empire_id == ALL_EMPIRES` and my ships were again attacked by monsters. But @geoffthemedio probably had a reason to add that check, so cant comment if that change is enough

**Comment by geoffthemedio** [comment]
https://github.com/freeorion/freeorion/commit/d091d066c4a5a5f7687964767d1657ade410337a#r46150421

**Comment by Oberlus** [comment]
09a0066 fixes this
