### ISSUE TITLE
Fails to build with Boost 1.69 (develop snapshot)

### ISSUE THREAD

**Issue by jbeich** [freeorion/freeorion#2308]
After https://github.com/boostorg/boost/pull/189 build fails, see [error log](https://ptpb.pw/0Qs1) and [missing files](https://reviews.freebsd.org/differential/changeset/?ref=585402)
```
CMake Error at /usr/local/share/cmake/Modules/FindBoost.cmake:2049 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.69.0

  Boost include path: /usr/local/include

  Could not find the following Boost libraries:

          boost_signals
```
Note, according to [Boost calendar](https://www.boost.org/development/) 1.69 release is planned sometime in December.

**Comment by o01eg** [comment]
Looks like it will affect 0.4.8 as well.

**Comment by geoffthemedio** [comment]
I thought the signals dependency was removed some time ago. Does this just require a change to a CMakeLists.txt ? Perhaps to change a default from signals to signals2 ?

**Comment by Vezzra** [comment]
Has this been fixed sufficiently by #2310? Can we close it as resolved?

**Comment by geoffthemedio** [comment]
Seemingly yes

https://github.com/freeorion/freeorion/pull/2310#issuecomment-433535906

**Comment by jbeich** [comment]
After boostorg/serialization@af46ac2da3e9 (post-Beta1) build fails. See [error log](https://ptpb.pw/mNxv). Including `<string>` just after `<memory>` in `combat/CombatEvent.h` appears to be enough to fix it.

```c++
In file included from combat/CombatEvent.cpp:1:
combat/CombatEvent.h:42:25: error: implicit instantiation of undefined template 'std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >'
    virtual std::string CombatLogDetails(int viewing_empire_id) const
                        ^
/usr/include/c++/v1/iosfwd:193:32: note: template is declared here
    class _LIBCPP_TEMPLATE_VIS basic_string;
                               ^
In file included from combat/CombatEvent.cpp:1:
combat/CombatEvent.h:43:14: error: implicit instantiation of undefined template 'std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >'
    { return std::string(""); }
             ^
/usr/include/c++/v1/iosfwd:193:32: note: template is declared here
    class _LIBCPP_TEMPLATE_VIS basic_string;
                               ^
```
